---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-registration
  labels:
    app: user-profile-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile-registration
  template:
    metadata:
      labels:
        app: user-profile-registration
    spec:
      containers:
        - name: user-profile-registration
          image: username/user-profile-registration:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-algorithm
  labels:
    app: matching-algorithm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-algorithm
  template:
    metadata:
      labels:
        app: matching-algorithm
    spec:
      containers:
        - name: matching-algorithm
          image: username/matching-algorithm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-result
  labels:
    app: matching-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-result
  template:
    metadata:
      labels:
        app: matching-result
    spec:
      containers:
        - name: matching-result
          image: username/matching-result:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: username/chat:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-profile-registration
  labels:
    app: user-profile-registration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-profile-registration


---


apiVersion: v1
kind: Service
metadata:
  name: matching-algorithm
  labels:
    app: matching-algorithm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matching-algorithm


---


apiVersion: v1
kind: Service
metadata:
  name: matching-result
  labels:
    app: matching-result
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matching-result


---


apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    app: chat
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chat

